
debug: 1 
# 1 to enable debug


###############################################################
# FishEye

fisheye: 1

matrix_D: "matrix_d.npy"
matrix_K: "matrix_k.npy"
array_DIM: "array_dim.npy"


###############################################################
# Perspective
matrix: 1
# 1 to load from file

sizeXmm: 490
sizeYmm: 580
# Always needed 

idtl: 13
idtr: 11
iddr: 15
iddl: 14

matrix_file: "calib_matrix.npy"
# Required for loading and saving calibrator obj
###############################################################
sub_file: "background.png"
