#############################################################
#                 CAMERA-CONFIG FILE
# 
##############################################################
enable_debug: 1 
# 1 to enable debug

#################################################################
# FishEye
#################################################################
enable_fisheye: 1

matrix_D: "calib_data/matrix_d.npy"
matrix_K: "calib_data/matrix_k.npy"
array_DIM: "calib_data/array_dim.npy"

#################################################################
# Perspective
#################################################################
enable_perpective_correction: 1

# |------> x
# |
# |
# |y
sizeXmm: 2150
sizeYmm: 2000

matrix_file: "calib_data/calib_matrix.npy"

#################################################################
# Background diff
#################################################################
threshold: 30

enable_background_diff_from_file: 0

sub_file: "calib_data/background.png"

#################################################################
# Object extractor
#################################################################
noise_size: 400

min_robot_size: 4000

#################################################################
# Points of interest.
#################################################################
points:
  A:
    x: 0
    y: 0
  B: 
    x: 100
    y: 100

#################################################################
#
#   EXPERTS ONLY
# 
#################################################################
#
# WORKFLOW RESIZE
#
img_resize_default: 1

img_resize_after_fish: 1

img_resize_after_perpective: 1

img_resize_display: 1/4

