#############################################################
#                 CAMERA-CONFIG FILE
# 
##############################################################
enable_debug: 0
enable_fps: 1
#################################################################
# FishEye
#################################################################
enable_fisheye: 1

matrix_D: "calib_data/matrix_d.npy"
matrix_K: "calib_data/matrix_k.npy"
array_DIM: "calib_data/array_dim.npy"

#################################################################
# Check camera pos
#################################################################
calib_check_time_in_sec: 120

loc_aruco_x: 400
loc_aruco_y: 400

#################################################################
# Perspective
#################################################################
enable_perpective_correction: 1

# |------> x
# |
# |
# |y
sizeXmm: 2150
sizeYmm: 2000

zeroxloc: 3000
zeroyloc: 2000

reduction: 4

matrix_file: "calib_data/calib_matrixYellow.npy"

#################################################################
# Background diff
#################################################################
threshold: 30

enable_background_diff_from_file: 0

sub_file: "calib_data/background.png"

#################################################################
# Object extractor
#################################################################
noise_size: 400

min_robot_size: 4000

# Between 0 and 1
obj_center_ratio: 0.11

#################################################################
# Points of interest.
#################################################################
points:
  A:
    x: 0
    y: 0
  B: 
    x: 100
    y: 100

#################################################################
#
#   EXPERTS ONLY
# 
#################################################################
#
# WORKFLOW RESIZE
#
img_resize_default: 1

img_resize_after_fish: 1

img_resize_after_perpective: 1

img_resize_display: 1.2
