#############################################################
#                 CAMERA-CONFIG FILE
# 
##############################################################
enable_debug: 0
enable_fps: 1
#################################################################
# FishEye
#################################################################
enable_fisheye: 1

matrix_D: "calib_data/matrix_d.npy"
matrix_K: "calib_data/matrix_k.npy"
array_DIM: "calib_data/array_dim.npy"

#################################################################
# Check camera pos
#################################################################
calib_check_time_in_sec: 1

loc_aruco_x: 358.25
loc_aruco_y: 132.5

loc_aruco_acceptable_diff: 1.1

#################################################################
# Perspective
#################################################################
enable_perpective_correction: 1

# |------> x
# |
# |
# |y
sizeXmm: 2150
sizeYmm: 2000

zeroxloc: 3000
zeroyloc: 2000

reduction: 4

matrix_file: "calib_data/calib_matrixYellow.npy"

#################################################################
# Background diff
#################################################################
threshold: 15

enable_background_diff_from_file: 0

sub_file: "calib_data/background.png"

#################################################################
# Object extractor
#################################################################
noise_size: 500

min_robot_size: 2000

# Between 0 and 1
obj_center_ratio: 0.11
robot_center_ratio: 0.4

#################################################################
# Points of interest.
#################################################################
points:
  1: 
    x: 100
    y: 100
    h: 10
    w: 10
    expected_h: 166
    expected_s: 90
    expected_v: 189
    tolerated_error: 4

#################################################################
#
#   EXPERTS ONLY
# 
#################################################################
#
# WORKFLOW RESIZE
#
img_resize_default: 1

img_resize_after_fish: 1

img_resize_after_perpective: 1

img_resize_display: 1.2
